export const SODAS = [
  {
    name: 'Tukola',
    price: 25,
    calories: 150,
    size: '500ml',
    available: true,
    sugar: 39,
    caffeine: 34,
    flavor: 'Cola clásica',
    rating: 4.5,
    ingredients: ['Agua carbonatada', 'Azúcar', 'Colorante', 'Ácido fosfórico', 'Aromas', 'Cafeína'],
    benefits: ['Energía instantánea', 'Sabor refrescante', 'Perfecta con hielo'],
  },
  {
    name: 'Pepsi',
    price: 22,
    calories: 140,
    size: '500ml',
    available: true,
    sugar: 41,
    caffeine: 38,
    flavor: 'Cola dulce',
    rating: 4.3,
    ingredients: ['Agua carbonatada', 'Jarabe maíz', 'Colorante', 'Ácido fosfórico', 'Aromas', 'Cafeína'],
    benefits: ['Sabor consistente', 'Disponible mundial', 'Variedad tamaños'],
  },
  {
    name: 'Fanta',
    price: 20,
    calories: 120,
    size: '500ml',
    available: true,
    sugar: 35,
    caffeine: 0,
    flavor: 'Naranja',
    rating: 4.2,
    ingredients: ['Agua carbonatada', 'Jugo naranja', 'Azúcar', 'Ácido cítrico', 'Aromas'],
    benefits: ['Sin cafeína', 'Sabor frutal', 'Vitamina C'],
  },
  {
    name: 'Lima',
    price: 18,
    calories: 100,
    size: '500ml',
    available: false,
    sugar: 28,
    caffeine: 0,
    flavor: 'Lima-Limón',
    rating: 4,
    ingredients: ['Agua carbonatada', 'Jugo lima', 'Stevia', 'Ácido cítrico', 'Aromas'],
    benefits: ['Bajas calorías', 'Sabor cítrico', 'Refrescante'],
  },
  {
    name: 'Manzana',
    price: 23,
    calories: 130,
    size: '500ml',
    available: true,
    sugar: 32,
    caffeine: 0,
    flavor: 'Manzana Canela',
    rating: 4.1,
    ingredients: ['Agua carbonatada', 'Jugo manzana', 'Azúcar morena', 'Canela', 'Aromas'],
    benefits: ['Sabor único', 'Aroma canela', 'Sin cafeína'],
  },
]
