/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbsoluteComponent: typeof import('./components/AbsoluteComponent.vue')['default']
    AnimetScroll: typeof import('./components/AnimetScroll.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChanceSectio: typeof import('./components/ChageSection/ChanceSectio.vue')['default']
    Dashboard: typeof import('./components/Dashboard/Dashboard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InformationComponent: typeof import('./components/informationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SodaInfo: typeof import('./components/InformationPart/SodaInfo.vue')['default']
    SodaModelComponent: typeof import('./components/sodaModel/SodaModelComponent.vue')['default']
  }
}
